--1.
Create database Kamenne_obklady

-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-12-22 15:00:22 SEÈ
--   site:      SQL Server 2012
--   type:      SQL Server 2012

--zmìny: pøipsani auto incrementu ke vsem entitam

--2.
CREATE TABLE Faktura 
    (
     ID_Faktura INTEGER NOT NULL IDENTITY(1,1) , 
     Datum_vystaveni DATETIME NOT NULL , 
     Datum_splatnosti DATE NOT NULL , 
     Variabilni_symbol NUMERIC (28) NOT NULL ,  
     Konstantni_symbol NUMERIC (28) NOT NULL , 
     Zakaznik_ID_zakaznik INTEGER NOT NULL , 
     Zamestnanec_ID_zamestnanec INTEGER NOT NULL , 
     Zaplaceno BIT NOT NULL 
    )
GO

ALTER TABLE Faktura ADD CONSTRAINT Faktura_PK PRIMARY KEY CLUSTERED (ID_Faktura)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Objednavka 
    (
     ID_Objednavka INTEGER NOT NULL IDENTITY(1,1)  , 
     Cislo_objednavky NUMERIC (28) NOT NULL , 
     Faktura_ID_Faktura INTEGER NOT NULL , 
     Prodejna_ID_prodejna INTEGER NOT NULL , 
	 Celkova_castka_k_zaplaceni INTEGER,
     ID_Faktura INTEGER NOT NULL 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    Objednavka__IDX ON Objednavka 
    ( 
     Faktura_ID_Faktura 
    ) 
GO

ALTER TABLE Objednavka ADD CONSTRAINT Objednavka_PK PRIMARY KEY CLUSTERED (ID_Objednavka)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE "Objednavka/Zbozi" 
    (
     "ID_Zbozi/objednavka" INTEGER NOT NULL IDENTITY(1,1), 
     Zbozi_ID_zbozi INTEGER NOT NULL , 
     Objednavka_ID_Objednavka INTEGER NOT NULL 
    )
GO

ALTER TABLE "Objednavka/Zbozi" ADD CONSTRAINT Relation_28_PK PRIMARY KEY CLUSTERED ("ID_Zbozi/objednavka")
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Prodejna 
    (
     ID_prodejna INTEGER NOT NULL IDENTITY(1,1)  , 
     Adresa VARCHAR (60) NOT NULL , 
     Kod_prodejny VARCHAR (10) NOT NULL 
    )
GO

ALTER TABLE Prodejna ADD CONSTRAINT Prodejna_PK PRIMARY KEY CLUSTERED (ID_prodejna)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Vyrobce 
    (
     ID_vyrobce INTEGER NOT NULL IDENTITY(1,1) , 
     Nazev VARCHAR (30) NOT NULL , 
     Zkratka VARCHAR (10) , 
     "E-mail" VARCHAR (30) NOT NULL 
    )
GO

ALTER TABLE Vyrobce ADD CONSTRAINT Vyrobce_PK PRIMARY KEY CLUSTERED (ID_vyrobce)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Zakaznik 
    (
     ID_zakaznik INTEGER NOT NULL IDENTITY(1,1) , 
     Jmeno VARCHAR (30) NOT NULL , 
     Prijmeni VARCHAR (30) NOT NULL , 
     "E-mail" VARCHAR (50) NOT NULL , 
     Telefon VARCHAR (15) NOT NULL 
    )
GO

ALTER TABLE Zakaznik ADD CONSTRAINT Zakaznik_PK PRIMARY KEY CLUSTERED (ID_zakaznik)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Zamestnanec 
    (
     ID_zamestnanec INTEGER NOT NULL IDENTITY(1,1)  , 
     Jmeno VARCHAR (30) NOT NULL , 
     Prijmeni VARCHAR (30) NOT NULL , 
     Pozice VARCHAR (20) NOT NULL , 
     Prodejna_ID_prodejna INTEGER NOT NULL 
    )
GO

ALTER TABLE Zamestnanec ADD CONSTRAINT Zamestnanec_PK PRIMARY KEY CLUSTERED (ID_zamestnanec)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Zbozi 
    (
     ID_zbozi INTEGER NOT NULL IDENTITY(1,1)  , 
     Kod VARCHAR (30) NOT NULL , 
     Cely_nazev VARCHAR (50) NOT NULL , 
     Vyrobce_ID_vyrobce INTEGER NOT NULL , 
     Cena INTEGER NOT NULL , 
     Pocet_ks_na_sklade INTEGER NOT NULL , 
     Merna_jednotka VARCHAR (30) NOT NULL 
    )
GO

ALTER TABLE Zbozi ADD CONSTRAINT Zbozi_PK PRIMARY KEY CLUSTERED (ID_zbozi)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Faktura 
    ADD CONSTRAINT Faktura_Zakaznik_FK FOREIGN KEY 
    ( 
     Zakaznik_ID_zakaznik
    ) 
    REFERENCES Zakaznik 
    ( 
     ID_zakaznik 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Faktura 
    ADD CONSTRAINT Faktura_Zamestnanec_FK FOREIGN KEY 
    ( 
     Zamestnanec_ID_zamestnanec
    ) 
    REFERENCES Zamestnanec 
    ( 
     ID_zamestnanec 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Objednavka 
    ADD CONSTRAINT Objednavka_Faktura_FK FOREIGN KEY 
    ( 
     Faktura_ID_Faktura
    ) 
    REFERENCES Faktura 
    ( 
     ID_Faktura 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Objednavka 
    ADD CONSTRAINT Objednavka_Prodejna_FK FOREIGN KEY 
    ( 
     Prodejna_ID_prodejna
    ) 
    REFERENCES Prodejna 
    ( 
     ID_prodejna 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE "Objednavka/Zbozi" 
    ADD CONSTRAINT Relation_28_Objednavka_FK FOREIGN KEY 
    ( 
     Objednavka_ID_Objednavka
    ) 
    REFERENCES Objednavka 
    ( 
     ID_Objednavka 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE "Objednavka/Zbozi" 
    ADD CONSTRAINT Relation_28_Zbozi_FK FOREIGN KEY 
    ( 
     Zbozi_ID_zbozi
    ) 
    REFERENCES Zbozi 
    ( 
     ID_zbozi 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Zamestnanec 
    ADD CONSTRAINT Zamestnanec_Prodejna_FK FOREIGN KEY 
    ( 
     Prodejna_ID_prodejna
    ) 
    REFERENCES Prodejna 
    ( 
     ID_prodejna 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Zbozi 
    ADD CONSTRAINT Zbozi_Vyrobce_FK FOREIGN KEY 
    ( 
     Vyrobce_ID_vyrobce
    ) 
    REFERENCES Vyrobce 
    ( 
     ID_vyrobce 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

Alter table Objednavka drop column ID_Faktura;
Alter table Zamestnanec drop column [Pozice];
Alter table [Objednavka/Zbozi] add Pocet_objednanych_ks INTEGER;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             1
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
